export interface Response {
  headline: string
  explanation: string
  doNow: string
  escalate: string
}

export const RESPONSES: Record<string, Response> = {
  // HEALTHY USER RESPONSES
  H_FV_S1_T1: {
    headline: 'Your body is fighting something off',
    explanation: 'A mild fever that just started today is your body doing its job. It is too early to worry but worth paying attention to.',
    doNow: 'Rest and drink plenty of water. Take your temperature if you can. You can take paracetamol for comfort — follow the dosage on the pack.',
    escalate: 'Check in with Aya tomorrow. If your fever rises above 38.5°C, has not improved in 48 hours, or new symptoms appear — get a malaria rapid test. In Ghana fever should never be ignored for too long.',
  },
  H_FV_S2_T2: {
    headline: 'A few days of fever needs attention',
    explanation: 'A moderate fever that has lasted a few days needs attention now. Your body has been fighting something for a while and it needs help.',
    doNow: 'Get a malaria rapid test today at a pharmacy or clinic. Keep drinking fluids and rest as much as you can.',
    escalate: 'Go to a clinic today if your temperature is above 39°C, you have chills, you feel confused or very weak, or the fever keeps rising.',
  },
  H_FV_S3_T2: {
    headline: 'Please do not manage this at home any longer',
    explanation: 'A severe fever that has lasted several days is serious.',
    doNow: 'Go to a clinic or pharmacy today for a malaria rapid test and evaluation. Severe fever for multiple days in Ghana needs professional attention.',
    escalate: 'Go to hospital now if you feel confused, have difficulty breathing, cannot keep water down, or the fever spikes suddenly.',
  },
  H_FV_S4: {
    headline: 'This is a medical emergency',
    explanation: 'An excruciating fever is a medical emergency.',
    doNow: 'Go to the nearest hospital or emergency department now. Do not wait. Do not manage this at home.',
    escalate: 'Go now and take someone with you if you can.',
  },
  H_FV_HD_S1_T1: {
    headline: 'Your body is reacting to something',
    explanation: 'Fever and headache together on the first day — your body is clearly reacting to something. This combination is very common with viral infections and early malaria in Ghana.',
    doNow: 'Rest in a cool quiet place. Drink water consistently — dehydration makes headaches worse. Paracetamol can help with both.',
    escalate: 'Check in with Aya tomorrow. If your fever rises above 38.5°C or the headache gets worse — get a malaria rapid test today not tomorrow.',
  },
  H_FV_HD_S2_T2: {
    headline: 'This is worth taking seriously today',
    explanation: 'Fever and a moderate headache lasting a few days is a combination worth taking seriously. In Ghana this pattern is one of the most common signs of malaria.',
    doNow: 'Get a malaria rapid test today. Most pharmacies have them and results come quickly. Rest and stay hydrated.',
    escalate: 'Go to a clinic today if your headache is getting worse not better, your fever is above 39°C, you feel sensitive to light, or you have a stiff neck.',
  },
  H_FV_HD_S3_T2: {
    headline: 'Please go to a clinic now',
    explanation: 'A severe headache with fever that has lasted several days needs professional attention today.',
    doNow: 'Go to a clinic now — not later today, now. A malaria test and basic examination will help identify what is causing this.',
    escalate: 'Go to hospital immediately if the headache is the worst you have ever felt, you have a stiff neck, you are sensitive to light, you feel confused, or you vomit repeatedly.',
  },
  H_FV_HD_S4: {
    headline: 'This is a medical emergency',
    explanation: 'A sudden severe headache described as the worst you have ever felt — especially with fever — is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Do not drive yourself if you can avoid it. Call someone or get to emergency care as quickly as possible.',
    escalate: 'Call 112 if you cannot get there safely.',
  },
  H_FV_HD_BA_S1_T1: {
    headline: 'Get a malaria test today',
    explanation: 'Fever, headache and mild body aches on the first day — this is a pattern Aya sees often, and in Ghana it deserves attention even when it feels manageable.',
    doNow: 'Get a malaria rapid test today. Do not wait to see if it improves — early treatment makes a significant difference. Rest and drink water consistently.',
    escalate: 'Check in with Aya tomorrow. If your fever rises above 38.5°C, aches worsen, or new symptoms appear — go to a clinic without delay.',
  },
  H_FV_HD_BA_S2_T2: {
    headline: 'Go for a malaria test today',
    explanation: 'Moderate fever, headache and body aches for a few days is a combination that needs attention today. In Ghana this is one of the most recognisable patterns of malaria.',
    doNow: 'Go to a pharmacy or clinic for a malaria rapid test now. If it comes back positive start treatment the same day. Keep drinking fluids.',
    escalate: 'Go to a clinic today if your fever is above 39°C, aches are getting worse not better, or you feel unusually weak or confused.',
  },
  H_FV_HD_BA_S3_T2: {
    headline: 'Please go to a clinic today',
    explanation: 'Severe body aches, fever and headache lasting several days — please do not manage this at home any longer.',
    doNow: 'Go to a clinic today. You need a malaria test and a proper examination.',
    escalate: 'Go to hospital now if you cannot walk properly, feel confused or drowsy, have a stiff neck, cannot keep water down, or your fever spikes suddenly.',
  },
  H_FV_HD_BA_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Excruciating body pain with fever and headache is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Do not wait. Take someone with you if possible.',
    escalate: 'Tell them your pain is severe when you arrive. Call 112 if you cannot get there safely.',
  },
  H_FV_CG_S1_T1: {
    headline: 'Your body is fighting something off',
    explanation: 'Fever and a mild cough on the first day usually point to a viral infection — your body is working on it.',
    doNow: 'Rest, drink warm fluids and keep your environment well ventilated. Get a malaria rapid test today — in Ghana fever should always prompt this check.',
    escalate: 'Check in with Aya tomorrow. Come back sooner if your cough produces yellow or green mucus, you develop chest pain, or breathing feels harder than usual.',
  },
  H_FV_CG_S2_T2: {
    headline: 'This needs attention today',
    explanation: 'A moderate cough with fever lasting a few days needs attention. This combination can sometimes signal a chest infection developing.',
    doNow: 'Go to a pharmacy or clinic today for a malaria test and evaluation. If your cough is producing mucus note the colour — yellow or green suggests a bacterial infection.',
    escalate: 'Go to a clinic today if your cough is getting worse not better, you have chest pain when you breathe or cough, or you feel short of breath.',
  },
  H_FV_CG_S3_T2: {
    headline: 'Please go to a clinic now',
    explanation: 'A severe cough with fever for several days needs professional attention today — not tomorrow.',
    doNow: 'Go to a clinic now. A severe cough with prolonged fever can indicate pneumonia or another chest infection that needs treatment.',
    escalate: 'Go to hospital now if you have difficulty breathing, chest pain when breathing, you cough up blood, or your lips or fingernails look bluish.',
  },
  H_FV_CG_S4: {
    headline: 'This is a medical emergency',
    explanation: 'An excruciating cough with fever is a medical emergency — particularly if breathing is difficult.',
    doNow: 'Go to the nearest hospital now. Tell the medical team you have severe cough fever and difficulty breathing.',
    escalate: 'Call 112 if you cannot get there safely.',
  },
  H_FV_CG_PROLONGED: {
    headline: 'A prolonged cough with fever needs evaluation',
    explanation: 'A cough that has lasted more than a week alongside fever needs careful evaluation — not just for common infections but also for tuberculosis which remains prevalent in Ghana.',
    doNow: 'Go to a clinic today. Tell them exactly how long you have had the cough.',
    escalate: 'Ask about a TB screening if they do not suggest it — there is no shame in asking. TB is treatable when caught early.',
  },
  H_SP_GENERAL_S1_T1: {
    headline: 'Rest your stomach today',
    explanation: 'Mild stomach discomfort that just started today is usually nothing serious — often related to something you ate or a mild digestive upset.',
    doNow: 'Rest your stomach. Drink small sips of water or oral rehydration salts. Plain foods like rice bread or bananas are gentle on the stomach.',
    escalate: 'Check in with Aya tomorrow. Come back sooner if pain worsens, you develop fever, or you cannot keep fluids down.',
  },
  H_SP_GENERAL_S2_T2: {
    headline: 'See a pharmacist today',
    explanation: 'Moderate stomach pain lasting a few days needs attention. This could be a digestive infection food poisoning that is lingering or something else worth checking.',
    doNow: 'Go to a pharmacy today. Stay hydrated — oral rehydration salts are better than plain water if you have been having diarrhoea or vomiting.',
    escalate: 'Go to a clinic today if you have fever alongside the pain, blood in your stool, you cannot keep fluids down, or the pain is getting worse.',
  },
  H_SP_GENERAL_S3_T2: {
    headline: 'Please go to a clinic today',
    explanation: 'Severe stomach pain for several days needs professional attention today.',
    doNow: 'Go to a clinic now. Severe abdominal pain that has persisted for days needs examination not home management.',
    escalate: 'Go to hospital emergency now if the pain is sudden and sharp, your abdomen feels hard or rigid, you have high fever with the pain, you see blood in vomit or stool, or you feel faint.',
  },
  H_SP_GENERAL_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Excruciating stomach pain is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Do not eat or drink anything. Tell the medical team the pain is severe and where it is located.',
    escalate: 'Call 112 if you cannot get there safely.',
  },
  H_SP_UPPER_S1_S2: {
    headline: 'See a pharmacist today',
    explanation: 'Pain in the upper abdomen can sometimes be related to the stomach lining, acid, or other digestive organs.',
    doNow: 'Avoid alcohol, spicy food, ibuprofen and aspirin — these irritate the stomach lining. See a pharmacist today.',
    escalate: 'Go to a clinic if pain is worse after eating, you have persistent nausea, you notice dark or tarry stools, or pain is not improving after a few days.',
  },
  H_SP_UPPER_S3_S4: {
    headline: 'Please go to a clinic now',
    explanation: 'Severe upper abdominal pain needs clinic or hospital attention today.',
    doNow: 'Go now. Upper abdominal pain at this severity could involve the stomach liver gallbladder or pancreas — all of which need professional evaluation.',
    escalate: 'Go to emergency now if pain radiates to your back or shoulder, you vomit blood or material that looks like coffee grounds, or you feel faint or collapse.',
  },
  H_BA_S1: {
    headline: 'Rest and rehydrate today',
    explanation: 'Mild body aches without fever are often caused by physical exertion, poor sleep, or dehydration.',
    doNow: 'Drink water, rest, and try gentle stretching. A warm bath can help relax sore muscles.',
    escalate: 'Check in with Aya if aches persist beyond 3 days or fever develops.',
  },
  H_BA_S2: {
    headline: 'Rest today and monitor',
    explanation: 'Moderate body aches without fever that are affecting your day could be muscular, viral, or related to dehydration.',
    doNow: 'Rest today. Drink plenty of water. Paracetamol can help with discomfort.',
    escalate: 'See a pharmacist if aches persist beyond 3 days. See a doctor if specific joints are swollen, you develop fever, or aches are in one location and worsening.',
  },
  H_BA_S3: {
    headline: 'Go to a clinic today',
    explanation: 'Severe body aches without fever need attention today.',
    doNow: 'Go to a clinic. Severe aches without an obvious cause like intense exercise should be evaluated.',
    escalate: 'Go to hospital now if you suddenly cannot move a limb, joints are visibly swollen and hot, or you develop fever alongside the pain.',
  },
  H_BA_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Excruciating body pain without fever needs emergency evaluation.',
    doNow: 'Go to the nearest hospital now.',
    escalate: 'Pain this severe needs immediate attention regardless of cause. Call 112 if needed.',
  },
  H_FT_S1: {
    headline: 'Your body is asking for rest',
    explanation: 'Feeling tired can simply mean your body needs more rest. Poor sleep, stress, dehydration and not eating enough are the most common causes.',
    doNow: 'Sleep early tonight. Drink water consistently through the day. Eat a proper meal.',
    escalate: 'Check in with Aya if tiredness persists beyond a week without an obvious cause.',
  },
  H_FT_S2: {
    headline: 'See a pharmacist today',
    explanation: 'Noticeable fatigue affecting your day is worth paying attention to. This could be anaemia, early malaria, viral infection or simply your body under stress.',
    doNow: 'See a pharmacist today — ask about a malaria test and whether a blood test for anaemia might be useful. Rest eat well and drink plenty of water.',
    escalate: 'See a doctor this week if fatigue persists beyond a week, you feel dizzy or short of breath alongside it, or you have no appetite.',
  },
  H_FT_S3: {
    headline: 'Go to a clinic today',
    explanation: 'Exhaustion that prevents you from functioning normally needs medical attention.',
    doNow: 'Go to a clinic today. Severe fatigue can signal anaemia, malaria, thyroid problems or other conditions that need a proper diagnosis.',
    escalate: 'Go to hospital now if you feel faint or collapse, have chest pain or difficulty breathing alongside the fatigue, or you cannot stay awake.',
  },
  H_FT_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Being unable to get up or function at all is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Call someone to help you get there.',
    escalate: 'Call 112 if you cannot move safely.',
  },
  H_ST_S1_T1: {
    headline: 'Warm fluids and rest today',
    explanation: 'A mild sore throat on the first day is usually the beginning of a viral infection — your immune system is already working on it.',
    doNow: 'Drink warm fluids. Honey in warm water or warm salt water gargling can soothe the throat. Rest your voice. Avoid cold drinks and dusty environments.',
    escalate: 'Check in with Aya tomorrow. See a pharmacist if it is not improving after 2 days.',
  },
  H_ST_S2_T2: {
    headline: 'See a pharmacist today',
    explanation: 'A moderate sore throat lasting a few days needs attention.',
    doNow: 'See a pharmacist today. If the throat is very red has white patches or you have swollen glands in your neck — you may have a bacterial infection that needs antibiotics.',
    escalate: 'Go to a clinic if you have difficulty swallowing, your voice is very hoarse, or fever develops alongside the sore throat.',
  },
  H_ST_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'A severe sore throat needs clinic attention today — especially if it is making swallowing or breathing difficult.',
    doNow: 'Go to a clinic now.',
    escalate: 'Go to hospital emergency now if you have difficulty breathing, cannot swallow at all, your throat is visibly swollen, or you are drooling because you cannot swallow saliva.',
  },
  H_DZ_SPINNING: {
    headline: 'Move slowly today',
    explanation: 'Brief spinning when you move or change position is usually benign positional vertigo — caused by tiny crystals in your inner ear shifting.',
    doNow: 'Move slowly when getting up or turning your head. Sit on the edge of the bed before standing. Drink water — dehydration worsens it.',
    escalate: 'See a pharmacist if it persists beyond a few days. Go to a clinic if dizziness is accompanied by hearing loss, ringing in the ears, or ear pain.',
  },
  H_DZ_LIGHTHEADED: {
    headline: 'Drink water and sit down',
    explanation: 'Feeling lightheaded when you stand up quickly is usually caused by dehydration or a temporary drop in blood pressure.',
    doNow: 'Drink water now. Stand up slowly — sit on the edge of your seat before rising fully. Eat something if you have not.',
    escalate: 'See a doctor if this happens frequently, you faint, or you are on blood pressure medication.',
  },
  H_DZ_CONSTANT: {
    headline: 'Go to a clinic today',
    explanation: 'Constant unsteadiness needs clinic evaluation today.',
    doNow: 'Go to a clinic today. This type of dizziness can have several causes that need a proper examination to identify.',
    escalate: 'Go to hospital now if you also have a severe headache, difficulty speaking, weakness on one side of your body, or blurred vision. These together can signal a stroke — call 112 immediately.',
  },
  H_DZ_SUDDEN: {
    headline: 'This needs emergency evaluation',
    explanation: 'Sudden severe dizziness with no warning needs emergency evaluation.',
    doNow: 'Go to the nearest hospital now or call 112.',
    escalate: 'Tell the medical team when it started, how severe it is, and whether you have any other symptoms like headache, chest pain or weakness in your limbs.',
  },
  H_CP_SHARP: {
    headline: 'Go to a clinic today',
    explanation: 'Sharp chest pain that occurs when you breathe or cough is often caused by inflammation of the lining around the lungs or a muscle strain — not the heart.',
    doNow: 'Go to a clinic today for evaluation. This type of pain should still be checked — especially if you have had a recent illness or infection.',
    escalate: 'Go to hospital now if breathing becomes difficult, pain spreads to your arm or jaw, or you feel faint.',
  },
  H_NA_S1_S2: {
    headline: 'Rest your stomach',
    explanation: 'Mild to moderate nausea is usually caused by something you ate, a viral infection, or dehydration.',
    doNow: 'Rest your stomach. Sip water or oral rehydration salts slowly. Avoid heavy spicy or greasy food. Ginger tea or plain crackers can help settle nausea.',
    escalate: 'See a pharmacist if nausea persists beyond 2 days. Go to a clinic if you are vomiting repeatedly and cannot keep fluids down.',
  },
  H_NA_S3_S4: {
    headline: 'Go to a clinic today',
    explanation: 'Severe nausea that is preventing you from keeping anything down needs attention today.',
    doNow: 'Go to a clinic today — dehydration from persistent vomiting can become serious quickly.',
    escalate: 'Go to hospital now if you see blood in vomit, vomit looks like coffee grounds, you feel faint, or you have severe abdominal pain alongside the nausea.',
  },
  H_RS_ITCHY: {
    headline: 'See a pharmacist today',
    explanation: 'Itchy red patches without other symptoms are often an allergic reaction or a skin condition. Think about what has changed recently — new soap, food, fabric or plant contact.',
    doNow: 'See a pharmacist today for a suitable antihistamine or cream. Avoid scratching — it worsens the rash and risks infection.',
    escalate: 'Go to a clinic if rash spreads, you develop swelling of the face or lips, or breathing becomes difficult — this can signal a severe allergic reaction.',
  },
  H_RS_FEVER: {
    headline: 'Go to a clinic today',
    explanation: 'A widespread rash with fever needs clinic evaluation today. In Ghana this combination can be caused by viral infections measles or other conditions that need proper diagnosis.',
    doNow: 'Go to a clinic today. Tell them when the rash appeared and when the fever started.',
    escalate: 'Go to hospital now if rash is spreading rapidly, you feel very unwell, have difficulty breathing, or the rash has purple or dark spots.',
  },

  // DIABETIC USER RESPONSES
  D_FV_HD_BA_S1_T1: {
    headline: 'I am glad you checked in',
    explanation: 'Fever, headache and body aches — even when mild — need a closer look when you have diabetes. Infections can affect your blood sugar quickly, sometimes before you notice other changes.',
    doNow: 'Check your blood sugar now. Then get a malaria rapid test today — do not wait. Keep drinking fluids, continue your diabetes medication, and try to eat something light even if your appetite is low.',
    escalate: 'Come back to Aya or see a doctor if your blood sugar is running high, you cannot keep fluids down, or symptoms worsen through the day.',
  },
  D_FV_HD_BA_S2_T2: {
    headline: 'Please go to a clinic today',
    explanation: 'Moderate fever, headache and body aches for a few days alongside diabetes is a combination that needs professional attention today.',
    doNow: 'Check your blood sugar immediately. Then go to a clinic — bring your medication list with you. A malaria test and blood sugar check together will give the doctor a clearer picture.',
    escalate: 'Go today — not tomorrow. Infections and elevated blood sugar together can escalate faster than expected.',
  },
  D_FV_HD_BA_S3_T2: {
    headline: 'Please do not wait on this',
    explanation: 'Severe body aches with fever when you have diabetes needs urgent attention.',
    doNow: 'Check your blood sugar right now before you do anything else. If it is very high that alone is a reason to go to hospital today. Go to a clinic or hospital today and bring your medication.',
    escalate: 'Go to emergency now if you feel confused or drowsy, cannot keep fluids down, blood sugar is dangerously high, or pain is worsening rapidly.',
  },
  D_FV_HD_BA_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Excruciating pain with fever when you have diabetes is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Check your blood sugar on the way if you can and tell the medical team you have diabetes the moment you arrive.',
    escalate: 'Do not manage this at home. Go now. Call 112 if you cannot get there safely.',
  },
  D_FV_CG_S1_S2: {
    headline: 'Check your blood sugar first',
    explanation: 'Fever and cough together when you have diabetes need attention from the start — respiratory infections can affect your blood sugar significantly.',
    doNow: 'Check your blood sugar now. Get a malaria rapid test today and keep your fluid intake up. Continue your diabetes medication and try small frequent meals if your appetite is low.',
    escalate: 'See a doctor today if blood sugar is running high, cough is producing coloured mucus, or you feel unusually short of breath.',
  },
  D_FV_CG_S3_S4: {
    headline: 'Go to a clinic or hospital now',
    explanation: 'Severe cough with fever when you have diabetes needs urgent care.',
    doNow: 'Go to the nearest clinic or hospital now. Tell them you have diabetes. Take your medication and your glucose meter with you if you have one.',
    escalate: 'Call 112 if you cannot get there safely.',
  },
  D_SP_S1_S2: {
    headline: 'Check your blood sugar first',
    explanation: 'Stomach pain when you have diabetes needs careful attention. Digestive problems are more common with diabetes and some stomach pain can be a sign of high blood sugar affecting the digestive system.',
    doNow: 'Check your blood sugar now. Stay hydrated and continue your medication even if your appetite is poor.',
    escalate: 'Go to a clinic today if blood sugar is running high, you cannot keep fluids down, pain is in the lower right abdomen, or pain is persistent and worsening.',
  },
  D_SP_S3_S4: {
    headline: 'Go to a clinic or hospital now',
    explanation: 'Severe stomach pain when you have diabetes needs urgent attention.',
    doNow: 'Check your blood sugar immediately then go to a clinic or hospital. Tell the medical team you have diabetes the moment you arrive.',
    escalate: 'Go to emergency now if you feel confused, are breathing rapidly, cannot keep anything down, or your blood sugar is very high.',
  },
  D_BA_S1_S2: {
    headline: 'Check your blood sugar first',
    explanation: 'Body aches when you have diabetes can sometimes be related to nerve sensitivity or circulation — especially if the aches are in your legs or feet.',
    doNow: 'Check your blood sugar now. Rest and stay hydrated.',
    escalate: 'See a doctor this week if aches are concentrated in your feet or legs, you have tingling or numbness alongside the pain, or aches persist beyond a few days.',
  },
  D_BA_S3_S4: {
    headline: 'Go to a clinic today',
    explanation: 'Severe body pain when you have diabetes needs clinic attention today.',
    doNow: 'Check your blood sugar immediately then go to a clinic. Tell them you have diabetes and describe exactly where the pain is worst.',
    escalate: 'Go to emergency if pain is excruciating, you feel confused, or blood sugar is very high.',
  },
  D_FT_S1_S2: {
    headline: 'Check your blood sugar now',
    explanation: 'Fatigue is one of the most common symptoms of blood sugar that is too high or too low.',
    doNow: 'Check your blood sugar now. If it is low — eat or drink something with sugar immediately. If it is high — drink water and contact your doctor today. If it is normal — rest eat well and monitor.',
    escalate: 'See a doctor this week if fatigue is persistent despite normal blood sugar readings.',
  },
  D_FT_S3_S4: {
    headline: 'Check your blood sugar immediately',
    explanation: 'Severe fatigue when you have diabetes needs urgent attention.',
    doNow: 'Check your blood sugar immediately. If it is very low or very high — go to hospital now.',
    escalate: 'Even if blood sugar seems normal go to a clinic today. Severe unexplained fatigue in diabetes always needs investigation.',
  },
  D_ST_S1_S2: {
    headline: 'See a pharmacist or clinic today',
    explanation: 'A sore throat when you have diabetes can develop into a more serious infection faster than usual — your immune response works differently.',
    doNow: 'See a pharmacist or clinic today. Check your blood sugar — infections can push it higher.',
    escalate: 'Go to a clinic today if throat is getting worse, you have fever, or blood sugar is running high.',
  },
  D_ST_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe sore throat when you have diabetes needs clinic attention today.',
    doNow: 'Go to a clinic now. Tell them you have diabetes. Check your blood sugar before you go.',
    escalate: 'Go to emergency if you have difficulty breathing or swallowing or blood sugar is very high.',
  },
  D_DZ_ANY: {
    headline: 'Check your blood sugar now',
    explanation: 'Dizziness when you have diabetes needs immediate attention — it can be a sign of low blood sugar which needs to be treated right away.',
    doNow: 'Check your blood sugar now. If it is low — eat or drink something sugary immediately and sit down. If it is normal or high — rest and drink water and see a clinic today if dizziness persists.',
    escalate: 'Go to emergency if you feel faint, confused, or cannot check your blood sugar and dizziness is severe.',
  },
  D_NA_ANY: {
    headline: 'Check your blood sugar now',
    explanation: 'Nausea when you have diabetes needs careful attention — it can be a sign of high blood sugar or diabetic ketoacidosis especially if accompanied by vomiting.',
    doNow: 'Check your blood sugar now. If it is very high go to hospital today. If it is normal rest and sip fluids slowly. Do not skip your diabetes medication even if you cannot eat.',
    escalate: 'Go to emergency if vomiting is persistent, blood sugar is very high, you feel confused, or you are breathing rapidly.',
  },
  D_RS_ANY: {
    headline: 'See a clinic today',
    explanation: 'Skin changes and rashes when you have diabetes deserve attention — diabetes affects skin healing and immune response.',
    doNow: 'See a clinic today for any rash that is spreading painful or accompanied by fever. Skin infections in diabetes can worsen quickly.',
    escalate: 'Go to emergency if the rash is rapidly spreading, feels warm or painful, or you have fever alongside it.',
  },

  // HYPERTENSIVE USER RESPONSES
  HT_FV_HD_BA_S1_T1: {
    headline: 'Check your blood pressure today',
    explanation: 'Fever and headache together when you have hypertension deserve careful attention. Headaches can sometimes be related to blood pressure changes — and fever adds another layer of stress on your body.',
    doNow: 'Take your blood pressure if you have a monitor at home. Get a malaria rapid test today. Continue your blood pressure medication — do not skip it even if you feel unwell.',
    escalate: 'See a doctor today if your blood pressure reading is unusually high, your headache is severe or at the back of your head, or you feel dizzy or short of breath.',
  },
  HT_FV_HD_BA_S2_T2: {
    headline: 'Go to a clinic today',
    explanation: 'Moderate fever, headache and body aches for a few days when you have hypertension needs professional attention today.',
    doNow: 'Check your blood pressure. Then go to a clinic for a malaria test and evaluation. Do not take ibuprofen or aspirin for the pain — use paracetamol only.',
    escalate: 'Go to hospital now if you have a severe headache at the back of your head, chest pain, difficulty breathing, or you feel confused.',
  },
  HT_FV_HD_BA_S3_T2: {
    headline: 'Go to a clinic now',
    explanation: 'Severe body aches with fever and headache when you have hypertension needs urgent attention today.',
    doNow: 'Go to a clinic now. Tell them you have hypertension and have had these symptoms for several days. Check your blood pressure before you go if you can.',
    escalate: 'Go to hospital emergency now if headache is at the back of your head or neck, you have chest pain or tightness, you feel confused or have blurred vision, or your blood pressure reading is very high.',
  },
  HT_FV_HD_BA_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Excruciating pain with fever when you have hypertension is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Tell the medical team you have hypertension the moment you arrive.',
    escalate: 'If you experience chest pain, difficulty breathing or sudden confusion on the way — call 112 immediately.',
  },
  HT_FV_CG_S1_S2: {
    headline: 'Continue your medication and get checked today',
    explanation: 'Fever and cough when you have hypertension — keep a close eye on this.',
    doNow: 'Continue your blood pressure medication — do not skip it even when unwell. Get a malaria rapid test today. Avoid decongestant medications like pseudoephedrine — they can raise blood pressure.',
    escalate: 'Check in with Aya tomorrow. See a doctor today if your blood pressure reading is unusually high or you develop chest tightness.',
  },
  HT_FV_CG_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe cough with fever when you have hypertension needs emergency attention.',
    doNow: 'Go to the nearest hospital now. Tell them you have hypertension the moment you arrive.Take your medication with you.',
    escalate: 'Call 112 if you have chest pain or difficulty breathing on the way.',
  },
  HT_SP_S1_S2: {
    headline: 'Avoid ibuprofen and see a pharmacist',
    explanation: 'Stomach pain when you have hypertension — check whether you take ibuprofen or aspirin regularly. These medications can cause stomach ulcers especially with long-term use.',
    doNow: 'See a pharmacist today. Stay hydrated and rest. If you regularly take ibuprofen tell your doctor.',
    escalate: 'Go to a clinic if pain is persistent, you have nausea or vomiting alongside it, or you notice any blood in your stool.',
  },
  HT_SP_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe stomach pain needs urgent attention regardless of your blood pressure history — but hypertension adds importance to getting evaluated quickly.',
    doNow: 'Go to a clinic or hospital now. Take your medication list with you.',
    escalate: 'Go to emergency if you have severe pain with high blood pressure reading, feel faint, have chest pain alongside stomach pain, or cannot keep fluids down.',
  },
  HT_BA_S1_S2: {
    headline: 'Use paracetamol not ibuprofen',
    explanation: 'Mild to moderate body aches when you have hypertension — avoid ibuprofen for pain relief.',
    doNow: 'Use paracetamol instead. Rest, drink water, and continue your blood pressure medication.',
    escalate: 'See a doctor if aches persist beyond a few days or you develop any chest discomfort alongside them.',
  },
  HT_BA_S3_S4: {
    headline: 'Go to a clinic today',
    explanation: 'Severe body pain when you have hypertension needs clinic attention today.',
    doNow: 'Check your blood pressure before you go. Go to a clinic today.',
    escalate: 'Go to hospital now if you have chest pain or tightness alongside the body pain or your blood pressure reading is very high.',
  },
  HT_FT_S1_S2: {
    headline: 'Check your medication with your doctor',
    explanation: 'Fatigue when you have hypertension — check whether you recently started or changed blood pressure medication. Some medications cause tiredness especially in the first few weeks.',
    doNow: 'Rest, drink water, and continue your medication.',
    escalate: 'See your doctor this week to discuss the fatigue — they may need to review your medication.',
  },
  HT_FT_S3_S4: {
    headline: 'Go to a clinic today',
    explanation: 'Severe fatigue with hypertension needs clinic attention today.',
    doNow: 'Check your blood pressure before you go. Go to a clinic today.',
    escalate: 'Go to hospital now if you have chest pain, shortness of breath, or feel faint alongside the fatigue.',
  },
  HT_DZ_ANY: {
    headline: 'Check your blood pressure now',
    explanation: 'Dizziness when you have hypertension needs careful attention. It can sometimes signal that your blood pressure is too high or too low — both are important to check.',
    doNow: 'Check your blood pressure now if you have a monitor. If reading is very high — go to a clinic today. If reading is normal — rest drink water and monitor through the day.',
    escalate: 'Go to hospital now if dizziness is sudden and severe, you have a headache at the back of your head alongside it, chest pain, or any weakness in your limbs.',
  },
  HT_ST_S1_S2: {
    headline: 'Avoid decongestant remedies',
    explanation: 'Sore throat when you have hypertension — avoid decongestant throat sprays and cold remedies containing pseudoephedrine as they can raise blood pressure.',
    doNow: 'Warm honey water and salt water gargling are safe. See a pharmacist and tell them you have hypertension before taking any medication.',
    escalate: 'See a clinic if throat worsens after 2 days or fever develops.',
  },
  HT_ST_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe sore throat needs clinic attention today.',
    doNow: 'Go to a clinic now. Tell them you have hypertension. Use paracetamol only — avoid ibuprofen.',
    escalate: 'Go to emergency if breathing or swallowing becomes difficult.',
  },
  HT_NA_ANY: {
    headline: 'Check your blood pressure',
    explanation: 'Nausea when you have hypertension — check your blood pressure. Some blood pressure medications can cause nausea especially when first started.',
    doNow: 'Sip water slowly. Rest. Continue your medication unless it is making you very unwell.',
    escalate: 'Call your doctor today if nausea is severe, you cannot keep your medication down, or blood pressure reading is very high alongside the nausea.',
  },

  // ASTHMATIC USER RESPONSES
  AS_FV_HD_BA_S1_T1: {
    headline: 'Keep your inhaler close today',
    explanation: 'Fever, headache and body aches when you have asthma needs watching carefully. Respiratory infections can trigger asthma symptoms even when they start with general symptoms like these.',
    doNow: 'Keep your reliever inhaler close. Get a malaria rapid test today. Rest in a well ventilated space — avoid dust smoke and strong smells while you are unwell.',
    escalate: 'Check in with Aya tomorrow. If you develop any chest tightness, wheezing or shortness of breath alongside these symptoms — that changes things significantly.',
  },
  AS_FV_HD_BA_S2_T2: {
    headline: 'Go to a clinic today',
    explanation: 'Moderate fever, headache and body aches for a few days when you have asthma needs attention today. Infections that linger can trigger asthma flares.',
    doNow: 'Go to a clinic today for a malaria test and evaluation. Tell them you have asthma. Keep your inhaler with you at all times while you are unwell.',
    escalate: 'Go to hospital now if you develop wheezing, chest tightness, or difficulty breathing at any point — do not wait for it to pass on its own.',
  },
  AS_FV_HD_BA_S3_S4: {
    headline: 'Go to a clinic or hospital now',
    explanation: 'Severe symptoms alongside asthma needs urgent attention.',
    doNow: 'Go to a clinic or hospital today. Bring your inhaler and tell them you have asthma. Severe infections can trigger serious asthma attacks.',
    escalate: 'Go to emergency immediately if you have any difficulty breathing, chest tightness, or wheezing that your inhaler is not relieving.',
  },
  AS_FV_CG_S1_T1: {
    headline: 'Keep your inhaler close — check in daily',
    explanation: 'Fever and cough when you have asthma needs careful attention from the very first day. Respiratory infections are one of the most common triggers for asthma attacks.',
    doNow: 'Keep your reliever inhaler close at all times. Get a malaria rapid test today. Rest in a clean well ventilated space — away from dust smoke cooking fumes and strong smells.',
    escalate: 'Check in with Aya every day while these symptoms continue. Come back immediately or go to a clinic if you develop any chest tightness wheezing or difficulty breathing.',
  },
  AS_FV_CG_S2_T2: {
    headline: 'Go to a clinic today',
    explanation: 'A moderate cough with fever lasting a few days when you have asthma needs clinic attention today. This is not a wait-and-see situation.',
    doNow: 'Go to a clinic today. Tell them you have asthma and have had cough and fever for several days. Take your inhaler with you.',
    escalate: 'Go to hospital emergency now if you have wheezing chest tightness or difficulty breathing that your inhaler is not fully relieving.',
  },
  AS_FV_CG_S3_S4: {
    headline: 'Go to hospital now',
    explanation: 'Severe cough with fever when you have asthma is a potential emergency.',
    doNow: 'Go to hospital now. Take your inhaler with you and tell the medical team you have asthma immediately upon arrival.',
    escalate: 'If you have any difficulty breathing right now — call 112. Do not drive yourself.',
  },
  AS_DB_ANY: {
    headline: 'Use your inhaler now',
    explanation: 'Breathing difficulty when you have asthma needs immediate attention.',
    doNow: 'Use your reliever inhaler now. Sit upright in a calm well ventilated space. If your inhaler is helping — rest and monitor closely. Check in with Aya in one hour.',
    escalate: 'Go to hospital emergency now if inhaler is not helping after 10 minutes, breathing is getting worse, you feel panicked, or your lips look bluish. Call 112.',
  },
  AS_BA_S1_S2: {
    headline: 'Rest and avoid triggers',
    explanation: 'Body aches when you have asthma — rest in a clean environment and avoid physical triggers while you recover.',
    doNow: 'Avoid ibuprofen. Use paracetamol for pain relief. Rest in a clean space.',
    escalate: 'Check in with Aya if you develop any chest tightness or breathing difficulty alongside the aches.',
  },
  AS_BA_S3_S4: {
    headline: 'Go to a clinic today',
    explanation: 'Severe body pain needs clinic attention today.',
    doNow: 'Go to a clinic today. Keep your inhaler close — physical stress can sometimes trigger asthma symptoms.',
    escalate: 'Go to hospital now if you develop any breathing difficulty or wheezing alongside the pain.',
  },
  AS_FT_S1_S2: {
    headline: 'Check your breathing',
    explanation: 'Fatigue when you have asthma can sometimes mean your breathing has been slightly restricted without you noticing — your body works harder to breathe and tires more easily.',
    doNow: 'Rest in a well ventilated space. Keep your inhaler close.',
    escalate: 'See a doctor this week if fatigue is persistent or you notice any chest tightness alongside it.',
  },
  AS_FT_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe fatigue when you have asthma needs clinic attention today.',
    doNow: 'Go to a clinic now. Take your inhaler. Tell them you have asthma and are severely fatigued.',
    escalate: 'Go to emergency if you have any breathing difficulty or chest tightness alongside the fatigue.',
  },
  AS_ST_S1_S2: {
    headline: 'Keep your inhaler close',
    explanation: 'Sore throat when you have asthma — upper respiratory infections frequently trigger asthma flares. Keep your inhaler close from today.',
    doNow: 'Warm fluids rest and avoid triggers. See a pharmacist if not improving after 2 days.',
    escalate: 'Come back to Aya immediately if you develop any chest tightness or wheezing alongside the sore throat.',
  },
  AS_ST_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe sore throat needs clinic attention today — especially with asthma.',
    doNow: 'Go to a clinic now. Take your inhaler. Tell them you have asthma.',
    escalate: 'Go to emergency if you have any breathing difficulty or wheezing.',
  },

  // SICKLE CELL USER RESPONSES
  SC_FV_ANY: {
    headline: 'Go to a clinic or hospital today',
    explanation: 'Fever with any other symptom when you have sickle cell disease is never something to monitor at home without guidance.',
    doNow: 'Go to a clinic or hospital today — even with mild symptoms. Fever in sickle cell can signal infection or the beginning of a crisis and needs early evaluation. Take your medications and any medical documents you have.',
    escalate: 'Go to hospital emergency now if pain increases rapidly, you develop difficulty breathing, your abdomen becomes swollen or painful, or you feel confused.',
  },
  SC_BA_S1_S2: {
    headline: 'Go to a clinic today',
    explanation: 'Body pain when you have sickle cell disease needs medical attention today — even without fever. Pain is often the first sign of a sickle cell crisis.',
    doNow: 'Go to a clinic or hospital today. Tell them you have sickle cell disease and describe where the pain is.',
    escalate: 'Go to emergency now if pain is severe rapidly worsening or you have chest pain or difficulty breathing alongside it. Call 112 if needed.',
  },
  SC_BA_S3_S4: {
    headline: 'Go to hospital emergency now',
    explanation: 'Severe body pain when you have sickle cell disease needs emergency attention immediately.',
    doNow: 'Go to the nearest hospital emergency department now. Tell them you have sickle cell disease and describe where the pain is.',
    escalate: 'Call 112 if you cannot get there safely. Do not wait.',
  },
  SC_CG_ANY: {
    headline: 'Go to a clinic today',
    explanation: 'Cough when you have sickle cell disease needs medical attention today. Chest symptoms in sickle cell can develop into Acute Chest Syndrome — a serious complication that needs early treatment.',
    doNow: 'Go to a clinic or hospital today. Tell them you have sickle cell disease and have a cough.',
    escalate: 'Go to hospital emergency immediately if you have chest pain difficulty breathing your pain increases rapidly or you feel very unwell. Call 112 if needed.',
  },
  SC_FT_ANY: {
    headline: 'Go to a clinic today',
    explanation: 'Fatigue when you have sickle cell disease needs medical attention — it can be a sign of anaemia or the early stages of a crisis.',
    doNow: 'Go to a clinic today. Tell them you have sickle cell disease.',
    escalate: 'Go to emergency now if fatigue is severe, you feel faint, have chest pain difficulty breathing or yellowing of your eyes.',
  },
  SC_SP_ANY: {
    headline: 'Go to a clinic or hospital today',
    explanation: 'Stomach or abdominal pain when you have sickle cell disease needs medical attention today — it can sometimes signal an abdominal crisis or organ involvement.',
    doNow: 'Go to a clinic or hospital today regardless of severity. Tell them you have sickle cell disease and describe exactly where the pain is.',
    escalate: 'Go to emergency now if pain is severe or rapidly worsening, your abdomen feels swollen or rigid, you have fever alongside the pain, or you feel faint. Call 112 if needed.',
  },
  SC_ST_ANY: {
    headline: 'Go to a clinic today',
    explanation: 'A sore throat when you have sickle cell disease needs medical attention today. Infections that seem minor can escalate quickly.',
    doNow: 'Go to a clinic today. Tell them you have sickle cell disease.',
    escalate: 'Go to emergency if fever develops, pain increases rapidly, or you feel very unwell.',
  },

  // PREGNANT USER RESPONSES
  P_FV_ANY_S1_S2: {
    headline: 'Go to a clinic today',
    explanation: 'Fever during pregnancy always needs prompt attention — even when symptoms feel mild. Your body and your baby wellbeing are both affected by fever.',
    doNow: 'Go to a clinic or antenatal care provider today. Get a malaria test. Do not take ibuprofen or aspirin. Paracetamol only for temporary relief — and only while you get to care.',
    escalate: 'Go to hospital now if you have abdominal pain or cramping, reduced baby movements, bleeding, or your fever is high and not responding to paracetamol.',
  },
  P_FV_ANY_S3_S4: {
    headline: 'Go to hospital now',
    explanation: 'Moderate to severe symptoms during pregnancy need urgent medical attention today.',
    doNow: 'Go to a hospital or maternity unit now. Take your antenatal card with you. Tell the medical team you are pregnant immediately.',
    escalate: 'Call 112 if you have severe abdominal pain, bleeding, feel your baby is not moving normally, or you feel very unwell.',
  },
  P_SP_LOWER_ANY: {
    headline: 'Go to a clinic or maternity unit today',
    explanation: 'Lower abdominal pain during pregnancy always needs prompt medical attention.',
    doNow: 'Go to a clinic hospital or maternity unit today — do not wait. Take your antenatal card with you.',
    escalate: 'Go to hospital emergency now if pain is severe or constant, you have bleeding or spotting, you feel your baby is not moving as usual, you have fever alongside the pain, or you feel faint.',
  },
  P_SP_UPPER_S2_S3_S4: {
    headline: 'Go to hospital now',
    explanation: 'Upper abdominal pain during pregnancy — especially if severe — can sometimes signal pre-eclampsia a serious condition that needs urgent evaluation.',
    doNow: 'Go to hospital now. Tell them you are pregnant and have upper abdominal pain. Take your antenatal card.',
    escalate: 'This is not something to monitor at home.',
  },
  P_NA_S1_S2: {
    headline: 'Small frequent meals help most',
    explanation: 'Nausea is extremely common in pregnancy — especially in the first trimester. You are not alone in this.',
    doNow: 'Small frequent meals help more than large ones. Ginger tea plain crackers and cold water are safe and often helpful. Eat something small before getting out of bed in the morning.',
    escalate: 'Tell your antenatal provider if nausea is significantly affecting your eating and drinking.',
  },
  P_NA_S3_S4: {
    headline: 'Go to a clinic or maternity unit today',
    explanation: 'Severe nausea and vomiting during pregnancy needs medical attention when it prevents you from keeping any food or fluid down.',
    doNow: 'Go to a clinic or maternity unit today. You may need fluids through a drip to prevent dehydration.',
    escalate: 'Go to hospital now if you cannot keep any fluids down for more than 24 hours, you feel very weak or faint, or you notice your urine is very dark.',
  },
  P_BA_S1_S2: {
    headline: 'Rest and use warm compresses',
    explanation: 'Mild body aches during pregnancy are common — especially in the back hips and legs as your body changes.',
    doNow: 'Rest use a warm compress on sore areas and sleep with a pillow between your knees if back pain is an issue.',
    escalate: 'See your antenatal provider if aches are severe, concentrated in your lower abdomen, or accompanied by any bleeding or reduced baby movements.',
  },
  P_BA_S3_S4: {
    headline: 'Go to a clinic or maternity unit today',
    explanation: 'Severe body pain during pregnancy needs medical attention today.',
    doNow: 'Go to a clinic or maternity unit now. Take your antenatal card.',
    escalate: 'Go to emergency if pain is in your lower abdomen you have bleeding reduced baby movements or you feel faint.',
  },
  P_FT_S1_S2: {
    headline: 'Rest and eat iron-rich foods',
    explanation: 'Fatigue during pregnancy — especially in the first and third trimesters — is very common and usually normal.',
    doNow: 'Rest when you can. Eat iron-rich foods like beans dark leafy vegetables and meat. Stay hydrated.',
    escalate: 'Tell your antenatal provider at your next visit — they may check your blood for anaemia which is common in pregnancy.',
  },
  P_FT_S3_S4: {
    headline: 'Go to a clinic today',
    explanation: 'Severe exhaustion during pregnancy needs medical attention today.',
    doNow: 'Go to your antenatal provider or a clinic today. Severe fatigue in pregnancy can sometimes signal anaemia infection or other conditions that need treatment.',
    escalate: 'Go to hospital now if you feel faint have difficulty breathing notice your baby is not moving normally or have any bleeding.',
  },
  P_DZ_MILD: {
    headline: 'Stand slowly and stay hydrated',
    explanation: 'Mild dizziness and lightheadedness are common during pregnancy — especially in the first trimester and when standing quickly.',
    doNow: 'Stand up slowly. Eat small frequent meals. Drink water consistently. Rest when you feel dizzy — sit or lie down immediately.',
    escalate: 'Tell your antenatal provider if it is happening frequently.',
  },
  P_DZ_SEVERE: {
    headline: 'Go to a clinic or maternity unit today',
    explanation: 'Severe or constant dizziness during pregnancy needs medical attention today.',
    doNow: 'Go to a clinic or maternity unit today. Take your antenatal card.',
    escalate: 'Go to emergency now if dizziness is sudden and severe, you faint, have blurred vision severe headache or abdominal pain alongside it.',
  },
  P_RS_ANY: {
    headline: 'Go to a clinic today',
    explanation: 'Any rash during pregnancy needs medical evaluation today — some infections that cause rashes can affect your baby.',
    doNow: 'Go to a clinic or your antenatal provider today. Take your antenatal card. Do not self-medicate with creams or antihistamines without asking a health professional first.',
    escalate: 'Go to hospital now if rash is accompanied by fever you feel very unwell or you have any concerns about your baby movements.',
  },
  P_ST_S1_S2: {
    headline: 'Safe remedies only during pregnancy',
    explanation: 'Sore throat during pregnancy — avoid most throat lozenges and sprays without checking with a health professional first.',
    doNow: 'Warm honey water and salt water gargling are safe. See a pharmacist or clinic today if not improving after 2 days. Tell them you are pregnant before taking any medication.',
    escalate: 'Go to clinic if fever develops alongside the sore throat.',
  },
  P_ST_S3_S4: {
    headline: 'Go to a clinic now',
    explanation: 'Severe sore throat during pregnancy needs clinic attention today.',
    doNow: 'Go to a clinic now. Tell them you are pregnant. Take your antenatal card.',
    escalate: 'Go to emergency if you have difficulty breathing or swallowing.',
  },

  // DIABETIC + HYPERTENSIVE USER RESPONSES
  D_HT_FV_HD_BA_S1_S2: {
    headline: 'Check blood sugar and blood pressure now',
    explanation: 'Managing both diabetes and hypertension means your body has less room for error when fighting an infection. Even mild fever with these symptoms needs attention today.',
    doNow: 'Check your blood sugar. Check your blood pressure. Then go to a clinic today with both your medication lists. Get a malaria test while you are there. Do not take ibuprofen.',
    escalate: 'Go to hospital now if blood sugar is very high blood pressure reading is unusually high you have chest pain feel confused or cannot keep fluids down.',
  },
  D_HT_FV_HD_BA_S3_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Severe symptoms with both diabetes and hypertension is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Check your blood sugar and blood pressure on the way if you can. Take all your medications.',
    escalate: 'Tell the medical team you have both conditions immediately upon arrival. Call 112 if you cannot get there safely.',
  },
  D_HT_FV_CG_S1_S2: {
    headline: 'Go to a clinic today',
    explanation: 'Cough and fever when you have both diabetes and hypertension needs clinic attention today — not tomorrow.',
    doNow: 'Check your blood sugar and blood pressure now before you go. Go to a clinic today with both your medication lists. Get a malaria test. Do not take ibuprofen or decongestant cold remedies.',
    escalate: 'Go to hospital now if blood sugar or blood pressure is very high you have chest pain or tightness or breathing feels harder than usual.',
  },
  D_HT_FV_CG_S3_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Severe cough with fever when you have both diabetes and hypertension is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Check blood sugar and blood pressure on the way if you can. Take all your medications.',
    escalate: 'Tell the medical team you have both conditions. Call 112 if you cannot get there safely.',
  },
  D_HT_SP_S1_S2: {
    headline: 'Check blood sugar and blood pressure first',
    explanation: 'Stomach pain when you have both diabetes and hypertension needs careful attention today.',
    doNow: 'Check your blood sugar and blood pressure now. Go to a clinic today. Do not take ibuprofen or aspirin — they affect both conditions.',
    escalate: 'Go to hospital now if blood sugar or blood pressure is very high pain is in the lower right abdomen you cannot keep fluids down or you feel faint.',
  },
  D_HT_SP_S3_S4: {
    headline: 'This is a medical emergency',
    explanation: 'Severe stomach pain with both diabetes and hypertension is a medical emergency.',
    doNow: 'Go to the nearest hospital now. Check blood sugar and blood pressure on the way. Take all your medications.',
    escalate: 'Tell the medical team you have both conditions immediately upon arrival.',
  },

  // OVERRIDE RESPONSES
  EMERGENCY_OVERRIDE: {
    headline: 'Please go to hospital now',
    explanation: 'What you have described needs emergency medical attention right away. Aya cannot safely assess this further.',
    doNow: 'Go to the nearest hospital emergency department now. Take someone with you if you can. Tell the medical team everything you told Aya — all your symptoms how long you have had them and your existing conditions.',
    escalate: 'Call 112 if you cannot get there safely. Do not wait.',
  },
  RED_FLAG_THUNDERCLAP: {
    headline: 'Please go to hospital now',
    explanation: 'A headache that came on suddenly and hit hard within minutes — especially with fever — is something Aya takes very seriously. This pattern needs emergency evaluation right away.',
    doNow: 'Go to the nearest hospital now. Do not drive yourself if you can avoid it. Call someone or get to emergency care as quickly as possible.',
    escalate: 'Tell the medical team the headache came on suddenly and is severe. Those words matter. Call 112 if needed.',
  },
  RED_FLAG_NECK: {
    headline: 'Please go to hospital now',
    explanation: 'Pain concentrated at the back of your head and neck combined with fever is a combination that needs urgent medical attention. This can sometimes be a sign of meningitis — a serious condition that responds well to early treatment.',
    doNow: 'Go to a hospital emergency department now. Tell them you have fever severe headache and neck pain.',
    escalate: 'Do not wait. Call 112 if you cannot get there safely.',
  },
  APPENDICITIS_FLAG: {
    headline: 'Go to a hospital or clinic now',
    explanation: 'Pain in the lower right side of your abdomen that is severe needs urgent evaluation today. This location is where your appendix sits — and severe pain there should always be checked by a doctor promptly.',
    doNow: 'Go to a hospital or clinic now. Tell them exactly where the pain is — lower right abdomen. Do not eat or drink anything until you have been seen.',
    escalate: 'Go to emergency immediately if the pain is constant and worsening you have fever alongside the pain the area feels hard or tender to touch or you feel nauseous and cannot keep anything down.',
  },
  STROKE_OVERRIDE: {
    headline: 'Call 112 now',
    explanation: 'The symptoms you are describing together — dizziness with sudden weakness speech difficulty or vision changes — can be signs of a stroke. This is a medical emergency.',
    doNow: 'Call 112 now or get to the nearest hospital immediately. Every minute matters with stroke. Do not wait. Do not drive yourself.',
    escalate: 'Tell the medical team your symptoms started suddenly. Those words matter.',
  },
  UNCERTAINTY_OVERRIDE: {
    headline: 'Please see a pharmacist or clinic today',
    explanation: 'The symptoms you have described are a combination that Aya wants to be careful with. Rather than give you guidance that might not fit your situation exactly — the safest thing is to have a health professional take a proper look.',
    doNow: 'Go to the nearest clinic today. You do not need to know exactly what is wrong — the clinic is the right place to find out.',
    escalate: 'If you feel very unwell are in severe pain have difficulty breathing or feel confused — go to hospital or call 112 instead.',
  },

  // FEELING GOOD RESPONSES
  FEELING_GOOD_H: {
    headline: 'That is genuinely good to hear',
    explanation: 'Checking in when you feel well is a habit worth keeping — it helps Aya understand what your normal looks like.',
    doNow: 'Keep drinking water eating well and moving your body a little today.',
    escalate: 'You are doing well. Come back to Aya whenever something feels off.',
  },
  FEELING_GOOD_D: {
    headline: 'Glad to hear it',
    explanation: 'On a good day like this — keep your routine going.',
    doNow: 'Check your blood sugar as usual take your medication and eat at regular times. Consistency on good days is what makes the difficult ones more manageable.',
    escalate: 'Keep it up. Come back to Aya whenever something feels different.',
  },
  FEELING_GOOD_HT: {
    headline: 'Good news',
    explanation: 'Use this good day as a reminder — good days are built on good habits.',
    doNow: 'Take your blood pressure medication drink water and try to include a short walk if you can.',
    escalate: 'Keep it up. Come back to Aya whenever something feels different.',
  },
  FEELING_GOOD_AS: {
    headline: 'Happy to hear you are feeling well',
    explanation: 'Keep your inhaler accessible even on good days.',
    doNow: 'Note what is working in your environment so you can protect it. Good days in asthma management are worth understanding.',
    escalate: 'Come back to Aya whenever something feels different.',
  },
  FEELING_GOOD_SC: {
    headline: 'Really glad to hear this',
    explanation: 'Your good days matter — protect them.',
    doNow: 'Rest well stay hydrated and keep warm if the weather is cool.',
    escalate: 'Come back to Aya whenever something feels different — even small changes are worth checking.',
  },
  FEELING_GOOD_P: {
    headline: 'Wonderful',
    explanation: 'Your body is doing remarkable work.',
    doNow: 'Keep up with your water intake antenatal vitamins and rest.',
    escalate: 'Come back to Aya whenever something feels different. Your antenatal provider is always your first call for any concerns.',
  },
}

export function getResponse(responseKey: string): Response {
  return RESPONSES[responseKey] || RESPONSES['UNCERTAINTY_OVERRIDE']
}
