import { useNavigate } from 'react-router-dom'
import {
  ClipboardPlus,
  Stethoscope,
  ChevronRight,
  Download,
} from 'lucide-react'
import { Screen } from '@/components/Screen'
import { Card } from '@/components/Card'
import { Button } from '@/components/Button'
import { EmptyState } from '@/components/Feedback'
import { useAya } from '@/lib/store'
import { symptomById, TRIAGE_META } from '@/lib/symptoms'
import { relativeDay, timeOfDay } from '@/lib/format'
import jsPDF from 'jspdf'

export function Records() {
  const navigate = useNavigate()
  const { checks, profile, meds } = useAya()

  const generatePDF = () => {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    let y = 20

    // Header with Aya branding
    pdf.setFontSize(24)
    pdf.setTextColor('#1A4D2E')
    pdf.text('Aya', pageWidth / 2, y, { align: 'center' })
    y += 8
    pdf.setFontSize(12)
    pdf.setTextColor('#666666')
    pdf.text('by Radix Studio', pageWidth / 2, y, { align: 'center' })
    y += 10
    pdf.setFontSize(16)
    pdf.setTextColor('#000000')
    pdf.text('Personal Health Summary', pageWidth / 2, y, { align: 'center' })
    y += 20

    // Patient Information Section
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Patient Information', 20, y)
    y += 8
    pdf.setFontSize(11)
    pdf.setFont('helvetica', 'normal')
    
    const patientInfo = [
      `Name: ${profile.name || 'Not provided'}`,
      `Age: ${profile.age || 'Not provided'}`,
      `Biological Sex: ${profile.sex === 'male' ? 'Male' : profile.sex === 'female' ? 'Female' : 'Unspecified'}`,
      `Conditions: ${profile.conditions.length > 0 ? profile.conditions.join(', ') : 'None'}`,
      `Marital Status: ${profile.maritalStatus.replace('-', ' ')}`,
      `Religion: ${profile.religion.replace('-', ' ')}`,
    ]
    
    patientInfo.forEach(info => {
      pdf.text(info, 20, y)
      y += 6
    })
    y += 10

    // Symptom History Section
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Symptom History', 20, y)
    y += 8
    
    if (checks.length === 0) {
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      pdf.text('No symptom checks recorded.', 20, y)
      y += 6
    } else {
      checks.forEach((check, index) => {
        if (y > pageHeight - 40) {
          pdf.addPage()
          y = 20
        }
        
        const meta = TRIAGE_META[check.level]
        const labels = check.symptomIds
          .map((id) => symptomById(id)?.label)
          .filter(Boolean) as string[]
        const dateStr = new Date(check.createdAt).toLocaleDateString(undefined, {
          weekday: 'short',
          month: 'short',
          day: 'numeric',
          year: 'numeric',
        })
        const timeStr = timeOfDay(check.createdAt)
        
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'bold')
        pdf.text(`${index + 1}. ${dateStr} at ${timeStr}`, 20, y)
        y += 6
        
        pdf.setFont('helvetica', 'normal')
        pdf.text(`Triage: ${meta.title}`, 25, y)
        y += 5
        pdf.text(`Symptoms: ${labels.join(', ') || 'None'}`, 25, y)
        y += 5
        pdf.setFontSize(10)
        pdf.setTextColor('#444444')
        pdf.text(`Recommendation: ${meta.headline}`, 25, y)
        y += 8
        pdf.setTextColor('#000000')
      })
    }
    y += 10

    // Current Medications Section
    if (y > pageHeight - 40) {
      pdf.addPage()
      y = 20
    }
    
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Current Medications', 20, y)
    y += 8
    
    if (meds.length === 0) {
      pdf.setFontSize(11)
      pdf.setFont('helvetica', 'normal')
      pdf.text('No medications recorded.', 20, y)
      y += 6
    } else {
      meds.forEach((med, index) => {
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'normal')
        pdf.text(`${index + 1}. ${med.name}`, 20, y)
        y += 5
        pdf.setFontSize(10)
        pdf.setTextColor('#444444')
        pdf.text(`   Dose: ${med.dose}`, 20, y)
        y += 5
        pdf.text(`   Schedule: ${med.schedule}`, 20, y)
        y += 8
        pdf.setTextColor('#000000')
      })
    }

    // Footer with disclaimer
    const footerY = pageHeight - 20
    pdf.setFontSize(9)
    pdf.setFont('helvetica', 'italic')
    pdf.setTextColor('#888888')
    pdf.text(
      'This document is generated by Aya and is not a medical record. Always consult a qualified health professional.',
      pageWidth / 2,
      footerY,
      { align: 'center', maxWidth: pageWidth - 40 }
    )

    pdf.save('aya-health-summary.pdf')
  }

  return (
    <Screen withNav>
      <header className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="font-display text-[26px] font-bold text-cloud">
            Health Record
          </h1>
          <p className="mt-1 text-[15px] text-cream/70">
            Every check-in you've shared with Aya.
          </p>
        </div>
        <Button
          size="md"
          variant="outline"
          onClick={generatePDF}
          leftIcon={<Download size={18} />}
        >
          Export PDF
        </Button>
      </header>

      {checks.length === 0 ? (
        <EmptyState
          className="mt-6"
          icon={<ClipboardPlus size={26} />}
          title="No records yet"
          description="When you run a symptom check and save it, it'll show up here for you to look back on."
          action={
            <Button size="md" onClick={() => navigate('/symptoms')}>
              Start a check-in
            </Button>
          }
        />
      ) : (
        <ul className="space-y-3">
          {checks.map((check) => {
            const meta = TRIAGE_META[check.level]
            const labels = check.symptomIds
              .map((id) => symptomById(id)?.label)
              .filter(Boolean) as string[]
            return (
              <li key={check.id}>
                <Card accent="green" className="py-4">
                  <div className="flex items-center gap-3">
                    <span
                      className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-obsidian"
                      style={{ backgroundColor: meta.colorVar }}
                    >
                      <Stethoscope size={20} />
                    </span>
                    <div className="flex-1">
                      <p className="text-[15px] font-semibold text-cloud">
                        {meta.title}
                      </p>
                      <p className="text-xs text-cream/55">
                        {relativeDay(check.createdAt)} ·{' '}
                        {timeOfDay(check.createdAt)}
                      </p>
                    </div>
                    <ChevronRight size={18} className="text-cream/35" />
                  </div>
                  {labels.length > 0 && (
                    <div className="mt-3 flex flex-wrap gap-1.5">
                      {labels.map((label) => (
                        <span
                          key={label}
                          className="rounded-full bg-white/[0.06] px-2.5 py-1 text-xs text-cream/80"
                        >
                          {label}
                        </span>
                      ))}
                    </div>
                  )}
                </Card>
              </li>
            )
          })}
        </ul>
      )}
    </Screen>
  )
}
